### ISSUE TITLE
Noob needs help installing

### ISSUE THREAD

**Issue by Oznerologos** [M-1-RLG/io_scene_cmb#2]
Hello there :D 

I started a journey to get oot 3D models, managed to extract assets, unzip .zar files and ended up here with my .cmb files.
I've never used blender and have absolutly no idea how to use yours in blender, could it be possible to get a small "install/usage" read.me ? 

Thanks !

Have a good one :)

**Comment by Oznerologos** [comment]
Managed to install (i guess) but i have no clue on how to import cmb files, drag'n'drop does nothing and i can't "open" a file directly in blender

**Comment by HeyItsFerraro** [comment]
> Managed to install (i guess) but i have no clue on how to import cmb files, drag'n'drop does nothing and i can't "open" a file directly in blender

I'm having the same issue, let me know if you find a way to import the OOT 3D models cause I'm looking too

**Comment by Oznerologos** [comment]
Okay @HeyItsFerraro , turned out i just didn't know how to use blender, i tried "opening" the .cmb files when i should have "imported" them : File > import > CtrModelBinary (.cmb)
